import React from "react";
import ReactDOM from "react-dom/client";
import { registerSW } from "virtual:pwa-register";
import App from "./App";
import "@/styles/global.css";

// Installs the service worker generated by vite-plugin-pwa, which precaches the
// app shell (JS/CSS/HTML/icons) so the app can load with no connection at all —
// separate from and complementary to the IndexedDB data layer in src/offline/,
// which handles actual question/progress caching and offline sync.
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
